### ISSUE TITLE
Request: Mocking FabricClient or ActorServiceProxy

### ISSUE THREAD

**Issue by WhitWaldo** [loekd/ServiceFabric.Mocks#107]
Hello - this is something I may be able to help out with if it needs building out, but thought I'd first check that I'm not just missing it somewhere.

I've got a few methods here and there that need to query every single actor that exists for various properties (yeah, heavy operation - I know). I do this with the following:

```
var fabricClient = new FabricClient();
var partitions = await fabricClient.QueryManager.GetPartitionListAsync(new Uri("serviceUri"));

foreach (var partition in partitions)
{
  var partitionInfo = (Int64RangePartitionInformation)partition.PartitionInformation;
  var actorServiceProxy = ActorServiceProxy.Create(serviceName, partitionInfo.LowKey);

  ContinuationToken? continuationToken = null;

  do {
    var page = await actorServiceProxy.GetActorsAsync(continuationToken, cancellationToken);
    //Do something with each of the actors in the page
    continuationToken = page.ContinuationToken;
  } while (continuationToken != null);
}
```

It seems to me that I can test that this behavior works if I've got something that is mocking FabricClient.QueryManager to return a fake partition list I can iterate through, then mock the ActorServiceProxy.Create to have it return a mocked instance for each of the parameters given.

Is there some aspect of this library that already covers mocking this scenario?

Thanks!

**Comment by loekd** [comment]
Hi, you can the proxy by injecting `MockActorProxyFactory` and calling `CreateActorServiceProxy` instead of using `ActorServiceProxy.Create` inline.

I'll have a look at how hard it would be to mock out the FabricClient. (PR's are most welcome)

**Comment by loekd** [comment]
FabricClient has no interface and it's sealed. It's going to require a layer of abstraction on top in order to be mockable.

**Comment by loekd** [comment]
Dependabot now checks daily for SF upgrades, so the time between new versions should be low.
