### ISSUE TITLE
TokenSource.Cancel() hang when releasing lock

### ISSUE THREAD

**Issue by moormoon** [loekd/ServiceFabric.Mocks#109]
Hello,

I found under certain scenarios, the "TokenSource.Cancel()" in Lock.cs's Release() hang, which caused TimeoutException on other threads that wait for the same lock.

I ran into this issue in a .net core unit test project. This issue is not consistently repro-able. I tried moving "TokenSource.Cancel()" to run in a separate thread, i.e., put a "Task.Run" to wrap it, which resolved the hang issue. 

The following post may explain why "TokenSource.Cancel()" hang:
https://stackoverflow.com/questions/52450528/cancellationtokensource-cancel-hangs

Would you mind publishing a nuget package with this fix?

Thanks,

**Comment by loekd** [comment]
Hi, 
Thanks for your comment.

Please try using version 4.2.6 - Call `CancellationTokenSource.CancelAfter(0)` instead of `CancellationTokenSource.Cancel` to prevent blocking.

**Comment by loekd** [comment]
closed after not hearing back
