### ISSUE TITLE
Please support service fabric 8

### ISSUE THREAD

**Issue by kgflying** [loekd/ServiceFabric.Mocks#115]
Please support service fabric 8

 4.2.9 does not support SF v8 which is min version of .net 5.

Thanks in advance.

**Comment by kgflying** [comment]
Is that any update? Thanks.

**Comment by loekd** [comment]
Hi, thanks for the feedback. V5 is now on NuGet:

https://www.nuget.org/packages/ServiceFabric.Mocks/5.0.0

**Comment by loekd** [comment]
Please note that I will accept PR's. Many people have contributed, so please join the community.
