### ISSUE TITLE
[BUG] - `MockReliableDictionary` doesn't notify on `Clear()` call

### ISSUE THREAD

**Issue by gtcooke94** [loekd/ServiceFabric.Mocks#120]
**Describe the bug**
`MockReliableDictionary` doesn't send `InternalDictionaryChanged` events for `Clear` operation.

https://github.com/loekd/ServiceFabric.Mocks/blob/49fc50adaf56f141b70caa159e3cdeff0041a0a0/src/ServiceFabric.Mocks/ReliableCollections/MockReliableDictionary.cs#L26-L43

It currently only supports `Added`, `Removed`, and `Updated`.

**To Reproduce**
1. Have code take action depending on a `ReliableDictionary.Clear()` being called.
2. Notice it doesn't get called when using the `MockReliableDictionary`

**Expected behavior**
The mock should notify on `ChangeType.Clear` similar to SF's `NotifyDictionaryChangedAction.Clear`

**Comment by loekd** [comment]
Thanks for your feature request. I've added support for this event in [v5.0.6](https://www.nuget.org/packages/ServiceFabric.Mocks/5.0.6)
Please let me know if it works for you.

**Comment by gtcooke94** [comment]
Thanks! My app is unfortunately locked into an older SF version right now, so I can't quickly test this, but it looks good

**Comment by loekd** [comment]
I'm closing this issue. Feel free to reopen if needed.
