### ISSUE TITLE
6.1.0 nuget is broken

### ISSUE THREAD

**Issue by alangoldman** [loekd/ServiceFabric.Mocks#135]
Updating to 6.1.0 broke our build, the `ServiceFabric.Mocks` namespace is no longer available. The nuget looks broken/mispackaged?
![image](https://user-images.githubusercontent.com/44842667/196803925-dd5c65f6-72d1-492b-aec1-6679a23473de.png)
![image](https://user-images.githubusercontent.com/44842667/196803962-ec6b411e-a760-4c9d-8310-739368771b06.png)

**Comment by loekd** [comment]
My apologies, somehow dotnet build and dotnet pack work differently on GHA than on my machine. Please target the [latest version 6.1.4](https://www.nuget.org/packages/ServiceFabric.Mocks/6.1.4)

**Comment by loekd** [comment]
Thank you! And thanks for reporting the issue of course. 👍
