### ISSUE TITLE
MockFabricClient seems pointless

### ISSUE THREAD

**Issue by cortex-mr** [loekd/ServiceFabric.Mocks#144]
The MockFabricClient class seems useless. It can't be passed anywhere where a FabricClient is needed and doesn't seem to have any methods for configuring what a method should return.

As we cannot mock the the actual FabricClient using a framework like Moq (due to FabricClient being sealed), this makes testing incredibly difficult. Is there something i'm missing, can I get some clarification on the intended use for the MockFabricClient?

**Comment by loekd** [comment]
Thanks for your feedback. You're absolutely right, at this time it's useless. I started to work on it and came to the same conclusion. Hope that the SF team one day decides to allow mocking, or adds an interface + factory.
