### ISSUE TITLE
Microsoft.ServiceFabric.Actions v7 dependency doesn't exist

### ISSUE THREAD

**Issue by mack0196** [loekd/ServiceFabric.Mocks#153]
ServiceFabricContrib.Mocks v1.0.8 depends on Microosoft.ServiceFabric.Actors  >= 7.0.1001.
Today there is no version > 6.
![image](https://user-images.githubusercontent.com/6463105/219136669-739f5221-8ad1-46a9-a01a-f2e192db9b04.png)
![image](https://user-images.githubusercontent.com/6463105/219136742-a3cfb7ca-b90e-41b5-9c6a-ddaf7b46a00d.png)

**Comment by loekd** [comment]
Hi @mack0196,
Sorry about this, I've rolled back to version [6.2.0](https://www.nuget.org/packages/ServiceFabric.Mocks/6.2.0) which targets SF 6.1.1436.
The SF version 7.0.1001 was never released to the public and unlisted.

**Comment by loekd** [comment]
I'm closing this issue, as I haven't heard back.

**Comment by mack0196** [comment]
Thank you.
