### ISSUE TITLE
GetReminder does not find mocked reminder of MockActorStateProvider

### ISSUE THREAD

**Issue by macgyver2k** [loekd/ServiceFabric.Mocks#16]
when i want to verify my actor is removing an existing reminder, i first need to call 
`GetReminder( String reminderName )`
to obtain the IActorReminder by name. unfortunately this throws a ReminderNotFoundException.

as far as i can see, this method does not even touch the mock state provider.

if this is the wrong approch to test unregistering a reminder, what would be the right way?

**Comment by loekd** [comment]
I've added an example that registers, validates, and unregisters a reminder. Do you see different behavior between test and non-test?

https://github.com/loekd/ServiceFabric.Mocks/blob/d42d3d3aa5160ff2f738a8a8ea5dc96833c6de5f/test/ServiceFabric.Mocks.Tests/ActorTests/ReminderActorTests.cs#L14

Try it out and please let me know if there's a problem.

**Comment by macgyver2k** [comment]
Thx for your sample. Looking at it shows me a different approach of mocking it. so there's another questions rising from it.

Like in your example, i would have to implement a public method in my actual actor implementation. Implementing it here just for the sake of mocking - the method is "unused" for any business purpose. I was hoping there was a REAL way of mocking a reminder via state providers or some way in this direction.

Do you see a path towards this external mocking? Anyway, I will go using your solution now.

**Comment by loekd** [comment]
the underlying code relies on service remoting, which I can't mock at this time. So I see no alternatives.
