### ISSUE TITLE
MockActorStateManager methods should throw exceptions

### ISSUE THREAD

**Issue by macgyver2k** [loekd/ServiceFabric.Mocks#17]
as expample, the AddStateAsync method in MockActorStateManager does not throw an InvalidOperationException if a state (key) already exists (in the dictionary). same for GetStateAsync.

[https://github.com/loekd/ServiceFabric.Mocks/blob/master/src/ServiceFabric.Mocks/MockActorStateManager.cs#L26](url)

can this be changed to throw the exceptions according to the real implementation?

[https://github.com/Azure/service-fabric-services-and-actors-dotnet/blob/develop/src/Microsoft.ServiceFabric.Actors/Runtime/ActorStateManager.cs#L32](url)

**Comment by loekd** [comment]
Thanks for your feedback, I've changed this and pushed v1.8.1 to address this.
