### ISSUE TITLE
Compatibility with Service Fabric SDK 2.7 preview

### ISSUE THREAD

**Issue by arnevandenberghe** [loekd/ServiceFabric.Mocks#19]
It appears VSTS 2017 hosted build agents recently had SF SDK 2.7 preview installed, breaking our Unit Tests that use ServiceFabric.Mocks:

`System.TypeLoadException: Method 'Initialize' in type 'ServiceFabric.Mocks.MockActorStateProvider' from assembly 'ServiceFabric.Mocks, Version=1.8.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.`

Any chance of creating a prerelease based on SDK 2.7 preview?
I am willing to create a PR, but some guidance may be needed since I am not very active in OS.

**Comment by loekd** [comment]
This one is out of my control whilst the preview SDK is unavailable, fortunately I've had contact with the SF team, a solution is coming within the next few days.

**Comment by loekd** [comment]
I've added a [preview branch,](https://github.com/loekd/ServiceFabric.Mocks/tree/preview) which can be used to reproduce the issue. (run the tests)
I can use some help to figure out why this exception happens tho.

**Comment by loekd** [comment]
I've published a preview package that targets the preview SDK and Nuget packages. That runs fine on the VS2017 build agents.
https://www.nuget.org/packages/ServiceFabric.Mocks/2.2.0-preview
