### ISSUE TITLE
Mock KeyedCollection for ConfigObject

### ISSUE THREAD

**Issue by CharlesZhong** [loekd/ServiceFabric.Mocks#24]
How to mock a KeyedCollection  during service initialization?

**Comment by loekd** [comment]
Can you provide more information about what you're trying to do and what problem you run into?

**Comment by CharlesZhong** [comment]
Actually there are many methods in Actor/Service would read configPackage to get configuration value.
According to the guide, i didn't find a way to mock ConfigurationPackage Object. So when I test my code, they just get null value from configPackage causing the i just used MockStatefulServiceContextFactory.Default.

Also the configPackage  of MockStatefulServiceContextFactory.Default is immutable. And I couldn't set value for the object.

Any ideas for  this one? Thank you.

**Comment by loekd** [comment]
I've added some functionality to test configuration package mocking, in v.2.2.3
Let me know if it works out for you.

**Comment by CharlesZhong** [comment]
Really appreciate for your support. It works fine for me and give me a way to inject configuration. That's very useful!

**Comment by loekd** [comment]
Glad you like it.
