### ISSUE TITLE
Mock and test multiple Stateful Services in one testrun

### ISSUE THREAD

**Issue by gverstraete** [loekd/ServiceFabric.Mocks#26]
Hello,

I'm struggling with the ability to test multiple statefull services in my Unit tests.  All tests work fine if they are executed seperately. But if the VSTS Test run Task executes them all together the task fails and shutdown unexpectedly. I think the issue resides on the ServiceFabric Mocks side since I'm using MockStatefulServiceContextFactory.Default. It doesn't help if I use the Create method of the factory for one of them. Could you please provide me some feedback about this or provide me with a workaround?

PS: we're running SF 2.5.216 so we are locked to 1.8.1 of the library.

Thanks!

**Comment by loekd** [comment]
I haven't had feedback from other people about any issues in that version. Can you provide more information about the error that occurs? Any stack strace info you can share?
Are you using a hosted 2015 or 2017 or custom agent?

**Comment by gverstraete** [comment]
Hi, We're using the default 2015 agent. The things we see in the build logs are these:

```
2017-08-22T10:22:58.0202646Z ##[error]Error: The active Test Run was aborted because the execution process exited unexpectedly. Check the execution process logs for more information. If the logs are not enabled, then enable the logs and try again.
2017-08-22T10:22:58.0202646Z ##[error]
2017-08-22T10:22:58.7870174Z 
2017-08-22T10:22:58.7880162Z Attachments:
2017-08-22T10:22:58.7880162Z   d:\a\1\s\xxxxx.coverage
2017-08-22T10:22:58.7880162Z 
2017-08-22T10:22:58.7880162Z Total tests: 180. Passed: 180. Failed: 0. Skipped: 0.
2017-08-22T10:22:58.7880162Z ##[error]Test Run Failed.
2017-08-22T10:22:58.7890171Z Test execution time: 33.1515 Seconds
2017-08-22T10:22:58.9340202Z Results File: d:\a\1\s\xxx.trx
2017-08-22T10:22:59.0310159Z ##[error]System.Exception: VSTest Test Run failed with exit code: 1
```
If I look into the trx I see exactly the same thing.

We spin up our services like this:
```
            var context = MockStatefulServiceContextFactory.Default;
                        _sut = new xxxxService(context);
```

I've also tried the MockStatefulSerivceContextFactory.Create, but the same behavior remains.

**Comment by loekd** [comment]
Thank you, and how did you see that the problem occurs inside `MockStatefulServiceContextFactory`? 
Can you try one build using the hosted 2017 agent and see if it happens there too?

**Comment by gverstraete** [comment]
The problem occurs when mocking 2 empty services and doesn't occur when mocking only one service. Services also run perfect in a cluster next to each other with a "normal" context. Due to some internal issues, I cannot build it with the hosted 2017 agent at the moment

**Comment by loekd** [comment]
Can you describe how reproduce the problem locally so I can debug?

**Comment by gverstraete** [comment]
Sorry for this late answer but due to some other descisions i wasn't aware of we moved from vsts to gitlab and we upgraded the service fabric versions. Since VSTS is closed I cannot give you feedback on that anymore.

For what I remember now, you could reproduce it by creating 2 statefull services in the same project and writing one unit test for each statefull service.

I did execute this code for each service:
```
           var context = MockStatefulServiceContextFactory.Default;
             _sut = new StatefullService(context);
```

Calling the second statefull service failed.

Thank you for all the support you gave!

**Comment by loekd** [comment]
Thank you for providing feedback. Can you please see if the problem occurs on the newer version, and if not, close the issue?
