### ISSUE TITLE
Needs to be updated to account for 2.8 SDK

### ISSUE THREAD

**Issue by dotnetgator** [loekd/ServiceFabric.Mocks#29]
At a minimum, classes that implement IActorStateProvider need to account for the new IStateProviderReplica2 interface, and those that implement IServiceProxy need to provide ServicePartitionClient2 endpoint. Using statements related to remoting also need to be changed to include V1 specification.

A deeper assessment of V1 vs V2 probably also needs to happen to determine if the Mocks need to be extended or split to handle the new communication tooling.

**Comment by MonDeveloper** [comment]
+1

**Comment by loekd** [comment]
The hosted build agent doesn't seem to have the latest bits installed yet. So the VSTS build doesn't work yet. I've published v2.3.0 manually.
beginning of v2 work: namespace ServiceFabric.Mocks.RemotingV2

**Comment by mj1856** [comment]
FYI, After upgrading to Service Fabric 2.8.211 and ServiceFabric.Mocks 2.3.2 I get a lot of these errors in my test output in our VSTS build server:

```
2017-10-11T21:09:45.8095452Z ##[error]Error Message:
2017-10-11T21:09:45.8095452Z ##[error]   Exception thrown while executing test. If using extension of TestMethodAttribute then please contact vendor. Error message: Could not load type 'Microsoft.ServiceFabric.Data.IStateProviderReplica2' from assembly 'Microsoft.ServiceFabric.Data.Interfaces, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
```
I'm pretty sure it's related to this item.

**Comment by loekd** [comment]
Yes, it is. I've been in contact with the SF team, hopefully the new SDK will be deployed to the VSTS agents soon.

**Comment by loekd** [comment]
The VSTS agents were updated. Your issues should now have disappeared. (Please confirm @mj1856 )

**Comment by mj1856** [comment]
It may be some time before I can verify.  I am using 2.7 for the time being.  Will try a 2.8 upgrade eventually and let you know.  Thanks.
