### ISSUE TITLE
MyStatefulActorTests.CreateActor() in example/tests is confusing

### ISSUE THREAD

**Issue by sandersaares** [loekd/ServiceFabric.Mocks#3]
The code for `CreateActor()` first configures an actor service with a factory method to create the actor (which new's up an instance of the actor class with the provided parameters) and thereafter it also new's up a new instance of the actor class, which it returns.

The reason for the two instantiation statements is not obvious. Very likely it is because I do not understand well enough the SF object lifetime management but my first impression is that I am confused regarding what the role of each new statement actually is. When is my actor created? Why does the other statement exist?

Some comments in the relevant code would be desirable, clarifying what the responsibilities of this code are in a mocking scenario and what the actual object flow is.

**Comment by loekd** [comment]
You're right. 
In v1.1.0 I've changed the code to always use the ActorService to create Actor instances. Hope this helps. Let me know.

**Comment by sandersaares** [comment]
Thanks! It is indeed much clearer now!
