### ISSUE TITLE
3.1.0 package missing from nuget

### ISSUE THREAD

**Issue by kasper3** [loekd/ServiceFabric.Mocks#40]
Readme says:

>3.1.0
> Upgraded nuget packages (SF 2.8.232)

But nuget doesn't agree https://www.nuget.org/packages/ServiceFabric.Mocks/

**Comment by loekd** [comment]
Sorry, apparently I ran out of build minutes.
I'll push manually tomorrow.

Sent from Nine<http://www.9folders.com/>
________________________________
Van: kasper3 <notifications@github.com>
verzonden: 21 nov. 2017 4:37 p.m.
Aan: loekd/ServiceFabric.Mocks
Cc: Subscribed
Onderwerp: [loekd/ServiceFabric.Mocks] 3.1.0 package missing from nuget (#40)


Readme says:

3.1.0
Upgraded nuget packages (SF 2.8.232)

But nuget doesn't agree https://www.nuget.org/packages/ServiceFabric.Mocks/

**Comment by loekd** [comment]
it's published: https://www.nuget.org/packages/ServiceFabric.Mocks/3.1.0

**Comment by kasper3** [comment]
Thanks!
