### ISSUE TITLE
Nuget package is missing strong name

### ISSUE THREAD

**Issue by NovemberZulu** [loekd/ServiceFabric.Mocks#41]
Could you please add strong name to the nuget? We are using ServiceFabric.Mocks internally at Microsoft, but unsigned libraries cause all kinds of inconveniences. Thank you!

**Comment by loekd** [comment]
Hi,
I've published v3.1.1 with a strong named assembly.
Please let me know if it works for you.

Sent from Nine<http://www.9folders.com/>
________________________________
Van: Maxim Nazarenko <notifications@github.com>
verzonden: 23 nov. 2017 14:49
Aan: loekd/ServiceFabric.Mocks
Cc: Subscribed
Onderwerp: [loekd/ServiceFabric.Mocks] Nuget package is missing strong name (#41)


Could you please add strong name to the nuget? We are using ServiceFabric.Mocks internally at Microsoft, but unsigned libraries cause all kinds of inconveniences. Thank you!

**Comment by NovemberZulu** [comment]
Seems to be better now :) I'll close the issue now. Thanks a lot!
