### ISSUE TITLE
Testing RunAsync in StatefulService

### ISSUE THREAD

**Issue by dotdestroyer** [loekd/ServiceFabric.Mocks#48]
When testing a StatefulService with your library, how do you make the RunAsync method start?  I have a processing loop in RunAsync that consumes from a queue which I need to run and test its behavior.

Is there a method to call on the StatefulService/Context, or something similiar?

```
var context = MockStatefulServiceContextFactory.Default;
_stateManager = new MockReliableStateManager();
_mockThing = new MockThing{};
var service = new TenantDispatcherService(context, _stateManager, _mockThing);

service.??????
context.?????
```

**Comment by dotdestroyer** [comment]
Kinda working around this for now by  exposing a public method on the StatefulService called RunInternalAsync which now does the work that was done in RunAsync.

```
        protected override async Task RunAsync(CancellationToken cancellationToken)
        {
            await RunInternalAsync(cancellationToken);
        }

        public async Task RunInternalAsync(CancellationToken cancellationToken)
        {
            var dispatchQueue = ...
        }
```

and then calling  RunInternalAsync from my test code 

```
             var service = new TenantDispatcher(context2, _stateManager, _mockWebhookDispatcherService);

            service.RunInternalAsync(_cancellationToken);
```

This works, but writing code purely to make testing possible is a bit of a smell. 

Interested to hear your thoughts on this!

Great Mock library btw, enjoying using it for my project :)

**Comment by loekd** [comment]
Thanks for the kind words!
Based on your feedback I've added `ServiceExtensions` to invoke non-public operations on Services in v3.1.7.
Let me know if that works out for you.

**Comment by dotdestroyer** [comment]
3.1.7 doesn't appear to be published on nuget...?

**Comment by loekd** [comment]
It's available now.
