### ISSUE TITLE
No support for .Net Standard or .Net Core

### ISSUE THREAD

**Issue by Scythen** [loekd/ServiceFabric.Mocks#49]
Need support for netcoreapp2.0 and netstandard2.0

**Comment by dotdestroyer** [comment]
netcoreapp2.0 is supported. I’m using it in two of my projects.

**Comment by Marusyk** [comment]
@ dotdestroyer yes, supported but with warning.

**Comment by Scythen** [comment]
@dotdestroyer the library does not support these frameworks, you are just using the old .csproj format which lets you reference full framework libraries. If you use the new project format with netcoreapp2.0 you cant reference this package.

Just created a pull request that adds support for netcoreapp2.0 and netstandard2.0 for V2 remoting.

**Comment by dotdestroyer** [comment]
Doh! My bad!! Apologies!

**Comment by loekd** [comment]
Resolved since v3.2.0
