### ISSUE TITLE
MockActorProxyFactory can't support an ActorId being assigned to multiple actor instances, but different types.

### ISSUE THREAD

**Issue by moswald** [loekd/ServiceFabric.Mocks#5]
It's perfectly valid to do something like this:

```csharp
var actorId = new ActorId(some_guid);
var actor_1 = _actorProxyFactory.CreateActorProxy<IMyActorType>(actorId);
var actor_2 = _actorProxyFactory.CreateActorProxy<IMyOtherActorType>(actorId);
```

but `MockActorProxyFactory` expects a single instance of `IActor` for each `ActorId` and so this scenario can't be mocked.

**Comment by moswald** [comment]
FYI, I plan on submitting a PR with a fix for this tomorrow.

**Comment by loekd** [comment]
Thanks for your contribution!
