### ISSUE TITLE
State Manager Rebuild Events while Testing Service Moves

### ISSUE THREAD

**Issue by charleszipp** [loekd/ServiceFabric.Mocks#56]
This issue only occurs while testing service moves using the new MockStatefulServiceReplicaSet.

When a stateful service primary moves to a new replica that was not originally part of the replica set, the rebuild event is triggered. This is the behavior we observed while our service is running on the cluster. However, this condition is not documented very thoroughly on the ASF docs. 

Currently, I do not believe rebuild events are being emitted from the `MockReliableStateManager` under this condition. This is because we have to share the same instance of the `MockReliableStateManager` for all replicas to simulate the replicas' state keeping in state with each other. The trade off is the `MockReliableStateManager` cant track the role for the specific replica hosting its instance. We would need this to be able to know when the replica is transitioning from Unknown -> Idle/Active Secondary. This transition is when the state manager's rebuild event is triggered.

The rebuild i believe is to allow a new replica to subscribe to all reliable states currently being managed by the replica set as it comes into the fold. Without this, the new node will not be able to subscribe to events like DictionaryChanged.

I believe the first part to allowing the simulation of this event is to allow for different State manager instances to be inserted into each replica. This will allow the state manager to observe the role of its owning replica. That will then allow it to trigger events during the role transitions.

The second part of the solution is how to keep the State manager instances in sync with each other. To do this I believe there are two options. First, we inject into the state manager or the mock reliable states a singleton dictionary so that all the state managers save their data to a single location. The drawback to this solution is it makes the creation of the `MockReliableStateManager` much more complex. It puts more burden on the consumers of this package. The other option would be to add some sort of eventing between the state manager instances to simulate them staying in sync. 

I wanted to get some input on whether to use injection of single dictionaries or events before i push a PR with a change to support this.

**Comment by charleszipp** [comment]
@loekd Yes, I mean the rebuild type of event fired on `StateManagerChanged`. There are 3; add, remove, and rebuild. The rebuild i observed happens when new replica is created during the first transition to idle secondary. In this case, we get the rebuild but, not the add/remove. So we lose our subscriptions to the new states added to the state manager

I will try to solve this via an event based approach. My initial thoughts were to create an actual event in the Transactional Dictionary. The transactional dictionary would be a single shared instance used by each different replica/instance of the state manager in play. This should make it less complex to keep the data between the different instances in sync while providing the event hooks to recreate this scenario.

I am working on creating a PR for this and will link it to this issue once i have it ready. Im at MSFT Build this week so may be next week before i can get something pushed. We have now a few teams using this library for testing stateful services. We havent quite cut over to this exact library for our app yet but definitely will be doing so in the future so we will need this capability.

**Comment by charleszipp** [comment]
I tried this branch and the event does not fire. When I first ran the test i got an exception i believe because some of the mocks are still trying to actually setup ports for a remoting listener. I then switched the call to change role from primary to idle secondary as this is when the event should fire. However, even in that case i did not get the event.

I added a handler in the `RemotingEnabledService` to `StateManagerChanged` to test this out. I then set a breakpoint under the Rebuild switch. The breakpoint was never hit.
```csharp
public RemotingEnabledService(StatefulServiceContext serviceContext, IReliableStateManagerReplica reliableStateManagerReplica) : base(serviceContext, reliableStateManagerReplica)
{
    this.StateManager.StateManagerChanged += StateManager_StateManagerChanged;
}

private void StateManager_StateManagerChanged(object sender, Microsoft.ServiceFabric.Data.Notifications.NotifyStateManagerChangedEventArgs e)
{
    switch(e.Action)
    {
        case Microsoft.ServiceFabric.Data.Notifications.NotifyStateManagerChangedAction.Rebuild:
            //BREAK HERE!
            var rebuild = e as Microsoft.ServiceFabric.Data.Notifications.NotifyStateManagerRebuildEventArgs;
            break;
    }
}
```

**Comment by loekd** [comment]
@charleszipp  I've added a few non functional changes. If you're happy with them, I'll release this intermediate version.
