### ISSUE TITLE
Nuget package is missing strong name

### ISSUE THREAD

**Issue by vinaychandra** [loekd/ServiceFabric.Mocks#60]
Could you please add strong name to the nuget? 

We are using ServiceFabric.Mocks internally at Microsoft, but unsigned libraries cause all kinds of inconveniences. Thank you!

**Comment by loekd** [comment]
Thanks for reporting this!
This should be fixed in v3.3.5
Please let me know if it works for you.

**Comment by vinaychandra** [comment]
It works! Thank you :)
