### ISSUE TITLE
Mock actor service with unknown implementation

### ISSUE THREAD

**Issue by joaocpribeiro** [loekd/ServiceFabric.Mocks#66]
My actor service is accessing another actor service that belongs to a different application and is not in the same solution. The interface is known (referenced throw nuget package) but the implementation is not, so we cannot initiate it with its constructor, as it is done in the examples.
Is there a way to mock this accessed actor service with ServiceFabric.Mocks?

**Comment by loekd** [comment]
Sure, for example, have a look at the unit tests in `[ActorCallerActorTests]` [here](https://github.com/loekd/ServiceFabric.Mocks/blob/master/test/ServiceFabric.Mocks.Tests/ActorTests/ActorCallerActorTests.cs#L19).
The Actor of type `ActorCallerActor` calls another Actor, `IMyStatefulActor`. ([here](https://github.com/loekd/ServiceFabric.Mocks/blob/master/test/ServiceFabric.Mocks.Tests/Actors/ActorCallerActor.cs#L24))
The `MockActorProxyFactory` is used to provide a test-time implementation, which does not need to be the same implementation as the run-time one. You decide what to return by either registering an actor  using `MockActorProxyFactory.RegisterActor` or by handling the event `MockActorProxyFactory.MissingActor`. 

Let me know if it works out for you.

**Comment by joaocpribeiro** [comment]
The examples helped to guide me to the solution, even though my case is quite different.
I do not have any implementation of the interface. I had to use Moq to mock the interface, which was not easy as well. Then I used the mocked object in RegisterActor.
Thank you for the hints.
