### ISSUE TITLE
MockActorService.Activate does not invoke OnActivateAsync

### ISSUE THREAD

**Issue by ygavrishov** [loekd/ServiceFabric.Mocks#7]
I does not know a way to test OnActivateAsync method via ServiceFabric.Mocks. Seems that it will be logical to invoke this protected method inside MockActorService.Activate.

**Comment by loekd** [comment]
Please upgrade to 1.3.2 or 1.4.0 and use this code to test OnActivateAsync:

```
var svc = MockActorServiceFactory.CreateActorServiceForActor<OnActivateActor>();
var actor = svc.Activate(new ActorId(Guid.NewGuid()));
await actor.InvokeOnActivateAsync();
```

**Comment by ygavrishov** [comment]
Thanks! It works!
