### ISSUE TITLE
Need example of how to mock the StatefulServiceBase.Partition property for resolving partition information

### ISSUE THREAD

**Issue by alexmarshall132** [loekd/ServiceFabric.Mocks#71]
Please add an example of how to create a mock for a StatefulSevice implementation that uses mocked partition information. The following code using reflection to try to set the Partition property does not work for the private setter for the StatefulServiceBase.Partition property because StatefulServicePartition does not implement IStatefulServicePartition (in 3.0.467)

			var partitionInformation = MockQueryPartitionFactory.CreateIntPartitonInfo(0, 3, Guid.NewGuid());

			Partition partition = MockQueryPartitionFactory.CreateStatefulPartition(partitionInformation, 1L, 1L, HealthState.Ok, ServicePartitionStatus.Ready, TimeSpan.MinValue, new Epoch());

			var statefulServiceContext = CreateMockStatefulServiceContext(mockConfigurationPackage, partitionInformation);

			this.sut = new MyStatefulService(
				context: statefulServiceContext
			);

			PropertyInfo propertyInfo = this.sut.GetType().GetProperty("Partition", BindingFlags.Instance | BindingFlags.NonPublic, null, null, new Type[0], null);

			propertyInfo.SetValue(this.sut, partition);

**Comment by loekd** [comment]
Hi @alexmarshall132 . Please upgrade to v3.4.1 and check out a unit test named [TestStatefulServiceWithMockPartition](https://github.com/loekd/ServiceFabric.Mocks/blob/master/test/ServiceFabric.Mocks.Tests/ServiceExtensions/ServiceExtensionsTests.cs#L89).

**Comment by loekd** [comment]
When using reflection to find a member, you must use type that declares the member. So for a stateful service, this would be:
 
```
var propertyInfo = typeof(StatefulServiceBase).GetProperty("Partition", BindingFlags.Instance | BindingFlags.NonPublic);
```
I've added some convenience methods to `ServiceExtensions` to get and [set ](https://github.com/loekd/ServiceFabric.Mocks/blob/master/src/ServiceFabric.Mocks/ServiceExtensions.cs#L167)partitions for services.
