### ISSUE TITLE
Issue with Mock Actor with CreateActorProxyFactory

### ISSUE THREAD

**Issue by simpleshobhit** [loekd/ServiceFabric.Mocks#78]
I have started using ServiceFabric.Mocks for mocking, I am testing a scenario where ACtor is called from a service, more specifically an API, which is .net core stateless service. Actor is being called from controller and I am writing unit tests for controller, I am mocking the Actor using mockActorProxyFactory, in the tests i get a correct instance of mockActorProxyFactory with all mocked data, but when in controller it tries to createActor proxy it returns always null
ActorProxyFactory.CreateActorProxy<TIActorInterface>(new ActorId(Id))   This line is always returning me null.
do we have a any such issue which is known, I am using 3.4.5 version of mocks and 3.4.624 version of service fabric.
Any help will be appreciated!
I am using the details given in link for Communication between Actors and Services
 https://loekd.wordpress.com/2018/03/05/unit-testing-in-azure-service-fabric/

**Comment by ThiemeNL** [comment]
Are you sure you are injecting the MockActorProxyFactory with the interface IActorProxyFactory into the controller as well?

**Comment by simpleshobhit** [comment]
Yes I am doing that , controller is like below.
Private IActorProxyFactory ActorProxyFactory;
public Test controller(IActorProxyFactory _ActorProxyFactory)
{
ActorProxyFactory = _ActorProxyFactory?? new ActorProxyFactory();
}

Buy whenever in controller I use this ActorProxyFactory to create actorproxy it returns null

**Comment by loekd** [comment]
Did you call the [RegisterActor](https://github.com/loekd/ServiceFabric.Mocks/blob/c8f3e5a594fbd262acf394ee1a9ceae866f46633/test/ServiceFabric.Mocks.Tests/ServiceTests/ActorCallerServiceTests.cs#L25) operation?

**Comment by simpleshobhit** [comment]
Func<ActorService, ActorId, ActorBase> actorFactory = (service, actorId) => new ThingsActorMock(service, id);

			var actorService = MockActorServiceFactory.CreateActorServiceForActor<ThingsActorMock>(actorFactory);
			var actor = actorService.Activate(id);

			var mockActorProxyFactory = new MockActorProxyFactory();
			mockActorProxyFactory.RegisterActor(actor);
			var facade = new ThingsFacade(mockActorProxyFactory);
			var test = facade.Test();

The Above is the Code in the unit tests that i am using for Mocking.
When in the Facade we use 
var test= ActorProxyFactory.CreateActorProxy<IThingActor>(new Uri("fabric:/Things/ThingActorService"),
				new ActorId(Guid.NewGuid()));
the value for test always comes to null

Please let me know if there is any issue in the implementation.

**Comment by loekd** [comment]
In your Facade, please ensure that you have the following code:
```
        public IActorProxyFactory ProxyFactory { get; }

        public ActorCallerService(StatelessServiceContext serviceContext, IActorProxyFactory proxyFactory = null) 
            : base(serviceContext)
        {
            ProxyFactory = proxyFactory ?? new ActorProxyFactory();
        }
```

And that you use the injected factory, instead of the static class `ActorProxyFactory` to create the proxy.

```
            var proxy = ProxyFactory.CreateActorProxy<IMyStatefulActor>(new ActorId(CalledActorId));
```

See [ActorCallerService ](https://github.com/loekd/ServiceFabric.Mocks/blob/c8f3e5a594fbd262acf394ee1a9ceae866f46633/test/ServiceFabric.Mocks.Tests/Services/ActorCallerService.cs)for the complete example.

**Comment by simpleshobhit** [comment]
This is the Facade Code private IActorProxyFactory ActorProxyFactory { get;}

		public ThingsFacade(IActorProxyFactory actorProxyFactory = null)
		{
			ActorProxyFactory = actorProxyFactory ?? new ActorProxyFactory();
		}

		public  Task Test()
		{
			var test= ActorProxyFactory.CreateActorProxy<IThingActor>(
				new ActorId(Guid.NewGuid()));
			return Task.CompletedTask;
		}

here the variable test becomes null.
see the below screen shot from test debugging
![image](https://user-images.githubusercontent.com/23196974/52253537-80580f80-292e-11e9-865b-bca4c7bd40b3.png)


The Actor Interface is defined as below:

[assembly: FabricTransportActorRemotingProvider(RemotingListenerVersion = RemotingListenerVersion.V2_1, RemotingClientVersion = RemotingClientVersion.V2_1)]
namespace ThingActor.Interfaces
{
	/// <summary>
	/// This interface defines the methods exposed by an actor.
	/// Clients use this interface to interact with the actor that implements it.
	/// </summary>
	public interface IThingActor : IActor
	{
		Task<string> GetThings();
		Task CreateThing(string thing);
		Task UpdateThing(string name);
	}
}

**Comment by ThiemeNL** [comment]
You should register your actor in the MockActorProxyFactory before you can call the mock actor. 
Read more about this: https://github.com/loekd/ServiceFabric.Mocks#mocking-out-called-actors

So change the new ActorId(Guid.NewGuid()) to an ActorId that you have registered in the MockActorProxyFactory.

**Comment by loekd** [comment]
@ThiemeNL  is spot on, either use pre-determined actor id's or use the [callback system](https://github.com/loekd/ServiceFabric.Mocks/blob/c8f3e5a594fbd262acf394ee1a9ceae866f46633/test/ServiceFabric.Mocks.Tests/ActorTests/ActorCallerActorTests.cs).

**Comment by loekd** [comment]
Thank you very much for the assistance @ThiemeNL ! 
Since we haven't heard back, I'll close this issue.
@simpleshobhit  feel free to reopen if you still encounter troubles.
