### ISSUE TITLE
No Servicefabric Mock package available for version 3.3.622 

### ISSUE THREAD

**Issue by simpleshobhit** [loekd/ServiceFabric.Mocks#79]
Hi ,
There is no package available which  points to the Service fabric packages for version 3.3.622
When using ServiceFabric.Mocks to version 3.4.3 which should support all version of service fabric greated than 3.2.187, I am getting error "System.TypeLoadException : Method 'CreateNonIServiceProxy' in type 'ServiceFabric.Mocks.MockServiceProxyFactory' from assembly 'ServiceFabric.Mocks, Version=3.4.3.0, Culture=neutral, PublicKeyToken=c8a3b3cecf8974ee' does not have an implementation"
Version 3.4.5 of the Mocks supports 3.3.624, which seems to have been deprecated by microsoft. Could you suggest which version of Mock should we use if we are using version 3.3.622 for service fabric

**Comment by loekd** [comment]
Hi, please use the new [v3.4.6](https://www.nuget.org/packages/ServiceFabric.Mocks/3.4.6). This has the downgraded package references. Let me know if this helps.
