### ISSUE TITLE
ActorStateManager Throws Exception when call TryGetStateAsync with ValueType not present

### ISSUE THREAD

**Issue by massimobonanni** [loekd/ServiceFabric.Mocks#8]
The MockActorStateManager throws exception when try to call TryGetStateAsync with a generic type ValueType and StateManager doesn't contains the key. 

I clone the repository and I fix the issue.
Can I authorize to pull request?

Max

**Comment by loekd** [comment]
Yes, pull requests are welcome.

**Comment by massimobonanni** [comment]
Ok, I try to do pull request.

**Comment by loekd** [comment]
I've just released a fix for the issue in v1.4.1. [Here](https://help.github.com/articles/creating-a-pull-request/)'s how you create a PR. 
Thank you for taking the time to report this issue!

**Comment by massimobonanni** [comment]
Ok, the problem was that I couldn't create a branch on the origin and I couldn't push the request.
Anyway, if you fix the problem, my push is not helpful.
Happy to help you.

Max
