### ISSUE TITLE
Replica Liseneters should open when ReplicaRole is Primary

### ISSUE THREAD

**Issue by VigoC** [loekd/ServiceFabric.Mocks#85]
Hi,

In MockStatefulServiceReplica th replica listeners are opened, before the role is set.
This resuls in no open listeners.

This is the change to fix the issue
![image](https://user-images.githubusercontent.com/49491316/55945027-3bac6580-5c4a-11e9-8f10-990c9ab83566.png)

This is the unit test that test the change:

[MockStatefulServiceReplicaTests.txt](https://github.com/loekd/ServiceFabric.Mocks/files/3067865/MockStatefulServiceReplicaTests.txt)

(I tried to push to a new branch to create a pull request but I get fatal error 403)

**Comment by loekd** [comment]
Thanks for reporting and fixing this @VigoC . The new build is running. v3.4.12 should resolve this for you.

**Comment by VigoC** [comment]
Thanks Loekd,
It is indeed resolved.
