### ISSUE TITLE
MockQueryServiceFactory.CreateStatelessServiceInstance - mismatch on param set on StatelessService- hasPersistedState being an extra

### ISSUE THREAD

**Issue by VaclavK** [loekd/ServiceFabric.Mocks#86]
running on SF SDK 3.3.644

**Comment by VaclavK** [comment]
@loekd do you want me to do PR?

**Comment by loekd** [comment]
Yes, please do. PR's are always welcome.

**Comment by loekd** [comment]
I've approved and rebased your PR. The new version should appear any minute.
