### ISSUE TITLE
failure when promoting and demoting replicas to different roles

### ISSUE THREAD

**Issue by ayonalan** [loekd/ServiceFabric.Mocks#88]
We'd like to be able to test our logic that kicks in during SF role transitions.
The following sequence of operations yields an error though:
            this.ReplicaSet = new MockStatefulServiceReplicaSet<TObj>(serviceFactory);
…
            await this.ReplicaSet.AddReplicaAsync(ReplicaRole.Primary, 1);
            await this.ReplicaSet.AddReplicaAsync(ReplicaRole.ActiveSecondary, 2);
...
            await this.ReplicaSet.PromoteActiveSecondaryToPrimaryAsync(2);

When added, the last step fails with the following error:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.ServiceFabric.FabricTransport, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. 

When FabricTransport dll reference is added, it fails with the following error:
System.Runtime.InteropServices.COMException: No such host is known. (Exception from HRESULT: 0x80072AF9).

That is, it seems to actually try and use the real transport, not a mock one.

What is the way to enable promotion and demotion of replicas to different roles using mock library?

Thanks,
-Ayse

**Comment by loekd** [comment]
Hi, I've added this unit test:

        [TestMethod]
        public async Task TestPromoteActiveSecondaryToPrimaryAsync()
        {
            Func<StatefulServiceContext, IReliableStateManagerReplica2, StatefulServiceWithReplicaListener> serviceFactory = (StatefulServiceContext context, IReliableStateManagerReplica2 stateManager) => new StatefulServiceWithReplicaListener(context);
            var replicaSet = new MockStatefulServiceReplicaSet<StatefulServiceWithReplicaListener>(serviceFactory);
            await replicaSet.AddReplicaAsync(ReplicaRole.Primary, 1);
            await replicaSet.AddReplicaAsync(ReplicaRole.ActiveSecondary, 2);
            await replicaSet.PromoteActiveSecondaryToPrimaryAsync(2);

            Assert.AreEqual(2, replicaSet.Primary.ReplicaId);
        }

It seems to be running just fine.
Are you certain that you're using the mock version of `serviceFactory`?

**Comment by ayonalan** [comment]
Yes I'm certain. Here's the test code that fails.

       public virtual async Task TestInitialize()
        {
            Func<StatefulServiceContext, IReliableStateManagerReplica2, TObj> serviceFactory =
                (context, stateManagerReplica) =>
                {
                    TObj service = this.CreateService(context, stateManagerReplica);
                    var partition = new MockStatefulServicePartition()
                    {
                        PartitionInfo = MockQueryPartitionFactory.CreateSingletonPartitonInfo()
                    };
                    service.SetPartition(partition);
                    return service;
                };

            this.ReplicaSet = new MockStatefulServiceReplicaSet<TObj>(serviceFactory);

            MockCodePackageActivationContext cxt =
                (MockCodePackageActivationContext)this.ReplicaSet.CodePackageActivationContext;
            cxt.ConfigurationPackage = GetTestConfiguration();

            await this.ReplicaSet.AddReplicaAsync(ReplicaRole.Primary, 1);
            await this.ReplicaSet.AddReplicaAsync(ReplicaRole.ActiveSecondary, 2);
            await this.ReplicaSet.PromoteActiveSecondaryToPrimaryAsync(2); // this line fails
        }

**Comment by ayonalan** [comment]
Thank you for trying this out Loek. It was the stateful service's CreateServiceReplicaListeners override that was causing this.  It creates remote replica listeners and mock DemoteToActiveSecondaryAsync method will try to close them. I'll close this issue.
