### ISSUE TITLE
Can I mock custom ActorService classes?

### ISSUE THREAD

**Issue by andrejohansson** [loekd/ServiceFabric.Mocks#9]
In your example you create a mocked actor using the following lines:

 ```
     Func<ActorService, ActorId, TActor> actorFactory = (service, actorId) => ...
      var svc = MockActorServiceFactory.CreateActorServiceForActor<TActor>(actorFactory);
      Actor = svc.Activate(id);
```

But how do I mock an actor which is using a custom ActorService? It´s initiated like this:

```
        ActorRuntime.RegisterActorAsync<CompanyActor>(
            (context, actorType) => new CustomActorService(context,
              actorType,
              (service, id) => new CompanyActor(service, id)))
          .GetAwaiter().GetResult();
```

How can I supply an instance or mock of my CustomActorService type?

**Comment by loekd** [comment]
Thanks for taking the time to provide feedback here. I've added support for custom ActorServices in v 1.5.0 please have a look at it and let me know if it works for your situation. 

Make sure to check [CustomActorServiceTests](https://github.com/loekd/ServiceFabric.Mocks/blob/master/test/ServiceFabric.Mocks.Tests/ActorTests/CustomActorServiceTests.cs) how it works.
