### ISSUE TITLE
MoveNextAysnc Not returning false with empty result

### ISSUE THREAD

**Issue by TKocoloski** [loekd/ServiceFabric.Mocks#91]
var collection = await _stateManager.GetOrAddAsync<IReliableDictionary2<Guid, long>>("Collection");

            using (var tx = _stateManager.CreateTransaction())
            {
          
                    var query = await collection.CreateEnumerableAsync(tx, key => (Something that has no matches), EnumerationMode.Unordered);

                    var list = new List<Guid>();

   This goes into infinite loop if the query returns an empty collection with a key value pair of null for both the key and the value.
                    while (await query.GetAsyncEnumerator().MoveNextAsync(new CancellationToken()))
                            list.Add(query.GetAsyncEnumerator().Current.Value.Id);

                    await tx.CommitAsync();

**Comment by loekd** [comment]
This is fixed in v3.4.13

**Comment by loekd** [comment]
Hi, I know it's been quite a while. 
Could you have a look at `InfiniteLoop_Issue91` in `MockReliableStateManagerTests` to see if you can add code to repro this issue? 
Thanks.
