### ISSUE TITLE
Package conflicts when using Service Fabric 6.5.641

### ISSUE THREAD

**Issue by MattHanMS** [loekd/ServiceFabric.Mocks#92]
There are several dependency conflicts when using the latest Service Fabric package (6.5.641) with ServiceFabric.Mocks.

**Comment by loekd** [comment]
Thanks for the feedback! A new version with matching SF dependencies is on it's way now:

- 3.4.16
    - upgraded to new SDK (SF 3.4.641)

Feel free to make a PR next time you encounter this.

________________________________
Van: MattHanMS <notifications@github.com>
Verzonden: donderdag 11 juli 2019 18:39
Aan: loekd/ServiceFabric.Mocks
CC: Subscribed
Onderwerp: [loekd/ServiceFabric.Mocks] Package conflicts when using Service Fabric 6.5.641 (#92)


There are several dependency conflicts when using the latest Service Fabric package (6.5.641) with ServiceFabric.Mocks.
