### ISSUE TITLE
Difference in Reminder runtime behavior?

### ISSUE THREAD

**Issue by serpentfabric** [loekd/ServiceFabric.Mocks#97]
The repro example can be found here:

https://github.com/serpentfabric/Sf.Mocks.IssueRepro

Basically, if you set a reminder that doesn't repeat, let it expire, and attempt to unregister it, the real runtime throws an exception but sf.mocks continues without error

**Comment by loekd** [comment]
Hi, thanks for your efforts so far! I've run your repro code, but it fails at `ReproActor.cs` line 41 `OnActivateAsync`. (not in `AssertAsync`)

> Microsoft.ServiceFabric.Actors.ReminderNotFoundException: 'Reminder ReproActor was not found for Actor repro'

This is because you're trying to get a reminder, that hasn't been registered yet. This happens after activation, in `ArrangeAsync`.

**Comment by serpentfabric** [comment]
Sorry for the ambiguity:

There are two projects to consider:
1) the Service Fabric Application itself named "ReminderExceptionRepro" -- which demonstrates how the actor behavior on top of the real service fabric subsystem
2) the unit test named "ReproActor.Test" -- which demonstrates how the actor runs behaves on top of the mock subsystem

If you debug the native service fabric application, then you are correct that a ReminderNotFound Exception is thrown when an attempt is made to get a reminder that has not been registered.

However, this is not the case for the mock subsystem: if you run the unit tests then a very different behavior occurs.

Hopefully this helps demonstrate my point.

**Comment by serpentfabric** [comment]
ah, shoot, i see what you're saying... doh...

**Comment by serpentfabric** [comment]
for posterity: if you're using service fabric.mocks and you don't call InvokeOnActivateAsync() on your actors then you will likely experience reminder behavior that is inconsistent with the runtime.

**Comment by serpentfabric** [comment]
before seriously considering the possibility i am going crazy, i decided to review the code that prompted this issue and after doing so i'm convinced it's worth re-investigation.

i did have to modify my repro... so you'll have to pull the latest changes.

here's what i've observed and continue to observe using the true runtime:
1. call some actor function that registers a reminder scheduled to fire once and never repeat some non-zero time in the future
a. saving a reference to that reminder as an instance variable of that actor before leaving said method
2. wait for that reminder to expire, in my example i made it do so immediately.
3. wait some arbitrary amount of time after expiration. 
a. i chose 10 seconds for my machine. 
b. if i waited less, the issue often didn't happen. 
c. you may need to wait longer.
d. call a different actor function that attempts to unregister the aforementioned reminder using the aforementioned reference
5. a ReminderNotFoundException is thrown by the native runtime
5.b. if not enough time has elapsed between the expiration of the reminder and the attempt to unregister said reminder using said instance than this exception shall not occur

if you set a breakpoint on the native sf app, you should see an exception like so:

```
   at Microsoft.ServiceFabric.Actors.Runtime.ActorManager.UnregisterReminderAsync(String reminderName, ActorId actorId, Boolean removeFromStateProvider)
   at ReminderExceptionRepro.ReproActor.UnregisterNonRepeatingReminderAsync(CancellationToken cancellationToken) in 
...
```

sf.mocks, when visualized from the test project, follows the same steps as above but differs in behavior for step 5 in that no exception is thrown. this is indicated by the failed test that expected the exception raised by the native runtime to also be raised by sf.mocks. hope this helps.
