### ISSUE TITLE
Deadlock issue in Tests

### ISSUE THREAD

**Issue by haithamkhedre** [loekd/ServiceFabric.Mocks#99]
I experienced deadlock issue in Tests specially when many tests sharing the Initialize I needed to synchronize the block to get it working :

Deadlock code to reproduce:

[TestInitialize]
        public virtual async Task TestInitialize()
        {
            //await SyncLock.WaitAsync();
            var partition = new MockStatefulServicePartition()
            {
                PartitionInfo = MockQueryPartitionFactory.CreateSingletonPartitonInfo(Guid.NewGuid())
            };

            this.VariantSettings = new Mock<IVariantSettings>(MockBehavior.Loose);

            Func<StatefulServiceContext, IReliableStateManagerReplica2, TObj> serviceFactory =
                (context, stateManagerReplica) =>
                {
                    // The mock library creates a new partition per instance; re-create the StatefulServiceContext with our singleton partition.
                    context = MockStatefulServiceContextFactory.Create(
                        context.CodePackageActivationContext,
                        context.ServiceTypeName,
                        context.ServiceName,
                        partition.PartitionInfo.Id,
                        context.ReplicaId);

                    TObj service = this.CreateService(context, stateManagerReplica);
                    service.SetPartition(partition);

                    return service;
                };

            this.ReplicaSet = new MockStatefulServiceReplicaSet<TObj>(serviceFactory);
            this.MockEventLogger = new Mock<IEventLogger>(MockBehavior.Loose);
            this.CacheClient = new Mock<ICacheClient>(MockBehavior.Strict);
            this.StoreResultCache = new Mock<IStoreResultCache<long>>(MockBehavior.Loose);

            MockCodePackageActivationContext cxt =
                (MockCodePackageActivationContext)this.ReplicaSet.CodePackageActivationContext;
            cxt.ConfigurationPackage = GetTestConfiguration();

            await this.ReplicaSet.AddReplicaAsync(ReplicaRole.Primary, 1);
            await this.ReplicaSet.AddReplicaAsync(ReplicaRole.ActiveSecondary, 2);

            this.Primary = this.ReplicaSet.Primary.ServiceInstance;
            this.Secondary = this.ReplicaSet.FirstActiveSecondary.ServiceInstance;
            //SyncLock.Release();
        }

**Comment by alexmarshall132** [comment]
I can confirm these issues exist. My team was on a tight schedule so we worked around them by switching our tests away from MSTest to XUnit

**Comment by loekd** [comment]
Sorry, it took a while to dive into this.
I was trying to repro your issue, and I have a few more questions:

1. Are you sharing properties (`Primary`, `Secondary`, `Replicaset`) at the class level within multiple tests that execute in parallel? 
2. If so, these properties would not have a predictable value during test execution (every test thread overwrites the value at a 'random' moment in time). Should you not use `ClassInitialize` instead?
3. If you need unique instances within tests, use factory methods instead of (shared) properties.

4. Can you help me out by providing a working repro using MSTest?

**Comment by haithamkhedre** [comment]
Yes your points are valid it is old test project need to be refactored, but when I saw the dead lock I reported it, it hung in these 2 lines 
           await this.ReplicaSet.AddReplicaAsync(ReplicaRole.Primary, 1);
            await this.ReplicaSet.AddReplicaAsync(ReplicaRole.ActiveSecondary, 2);

so if you can create dummy stateful service and  a method that have the 2 lines and a Test that spin multiple tasks or threads hit this method hopefully it will reproduce.

**Comment by loekd** [comment]
While I'm unable to repro, I did see that `MockStatefulServiceReplicaSet ` was not thread-safe. I've pushed a new version that uses a concurrent dictionary instead of a list:

> - 4.1.3 - MockStatefulServiceReplicaSet is now thread safe

Can you give it a go and provide feedback?

**Comment by haithamkhedre** [comment]
Thanks for the help, I did more tracing and found that the issue is on our project on replica close it trigger close action on our service which is the root for the issue I reported, I will close the issue :
  56.0%   CloseAsync  •  265,850 ms  •  ServiceFabric.Mocks.ReplicaSet.MockStatefulServiceReplica`1.CloseAsync()
    56.0%   InvokeOnCloseAsync  •  265,850 ms  •  ServiceFabric.Mocks.ServiceExtensions.InvokeOnCloseAsync(StatefulServiceBase, Nullable)
      56.0%   Invoke  •  265,850 ms  •  System.Reflection.RuntimeMethodInfo.Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
        56.0%   async OnCloseAsync  •  265,850 ms  •  Service.OnCloseAsync(CancellationToken)
          56.0%   OnClose  •  265,820 ms  •  Base`2.OnClose()
